//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONBON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BONBON()
        {
            this.PRIX_LOT = new HashSet<PRIX_LOT>();
            this.COMMANDEs = new HashSet<COMMANDE>();
        }
    
        public int BONBON_ID { get; set; }
        public string BONBON_TYPE { get; set; }
        public string BONBON_TEXTURE { get; set; }
        public string BONBON_COULEUR { get; set; }
        public Nullable<int> VARIANTE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIX_LOT> PRIX_LOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDEs { get; set; }
        public virtual VARIANTE VARIANTE { get; set; }
    }
}
