//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONBON
    {
        public int BONBON_ID { get; set; }
        public string BONBON_TYPE { get; set; }
        public string BONBON_TEXTURE { get; set; }
        public string BONBON_COULEUR { get; set; }
        public Nullable<int> VARIANTE_ID { get; set; }
    
        public virtual VARIANTE VARIANTE { get; set; }
    }
}
