//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUT
    {
        public int COUT_ID { get; set; }
        public string COUT_TYPE_BONBON { get; set; }
        public Nullable<int> COUT_FABRICATION { get; set; }
        public Nullable<int> COUT_CONDITIONNEMENT { get; set; }
        public Nullable<int> COUT_EXPEDITION { get; set; }
        public Nullable<int> COUT_GENERAL { get; set; }
    }
}
