//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYS
    {
        public int PAYS_ID { get; set; }
        public string PAYS_NOM { get; set; }
        public string PAYS_TRANSPORT { get; set; }
        public Nullable<decimal> RATIO_COMMANDE { get; set; }
        public Nullable<decimal> PAYS_RATIO_COMMANDE { get; set; }
    }
}
