//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERF_COMMANDES
    {
        public int PERF_ID { get; set; }
        public Nullable<int> COMMANDE_ID { get; set; }
        public Nullable<decimal> TEMPS_FABRICATION_LOT { get; set; }
        public Nullable<decimal> TEMPS_CONDITIONNEMENT { get; set; }
        public Nullable<int> BONBON_FABRIQUE_COUNT { get; set; }
        public Nullable<int> PERF_MACHINE_FABRICATION_ID { get; set; }
        public Nullable<int> PERF_MACHINE_CONDITIONNEMENT_ID { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
    }
}
