//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIX_LOT
    {
        public int PRIX_LOT_ID { get; set; }
        public Nullable<decimal> PRIX_LOT_PRIX { get; set; }
        public Nullable<int> BONBON_ID { get; set; }
        public Nullable<int> CONDITIONNEMENT_ID { get; set; }
    
        public virtual BONBON BONBON { get; set; }
        public virtual CONDITIONNEMENT CONDITIONNEMENT { get; set; }
    }
}
