//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTON
    {
        public int CARTON_ID { get; set; }
        public Nullable<int> CARTON_QUANTITE_LOT { get; set; }
        public Nullable<int> CARTON_ID_GARE { get; set; }
        public Nullable<int> COMMANDE_ID { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
    }
}
