//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_FABRICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MACHINE_FABRICATION()
        {
            this.VARIANTEs = new HashSet<VARIANTE>();
        }
    
        public int MACHINE_FABRICATION_ID { get; set; }
        public Nullable<int> MACHINE_FABRICATION_CHANGEMENT_OUTIL { get; set; }
        public Nullable<int> MACHINE_FABRICATION_CADENCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VARIANTE> VARIANTEs { get; set; }
    }
}
