//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETTE
    {
        public int RECETTE_ID { get; set; }
        public string RECETTE_TYPE { get; set; }
        public Nullable<int> RECETTE_ADDITIF { get; set; }
        public Nullable<int> RECETTE_ENROBAGE { get; set; }
        public Nullable<int> RECETTE_GELIFIANT { get; set; }
        public Nullable<int> RECETTE_AROME { get; set; }
        public Nullable<int> RECETTE_SUCRE { get; set; }
    }
}
