//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAUX_VENTES
    {
        public int TAUX_VENTE_ID { get; set; }
        public string TAUX_VENTE_BONBON { get; set; }
        public Nullable<int> TAUX_VENTE_ANNEE { get; set; }
        public Nullable<decimal> TAUX_VENTE_VALEUR { get; set; }
    }
}
