//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORT_INFO
    {
        public int TRANSPORT_INFO_ID { get; set; }
        public string TRANSPORT_INFO_TYPE_TRANSPORT { get; set; }
        public Nullable<int> TRANSPORT_INFO_QUANTITE_PALETTE { get; set; }
        public Nullable<int> TRANSPORT_INFO_CARTON_PAR_PALETTE { get; set; }
    }
}
