//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIANTE
    {
        public int VARIANTE_ID { get; set; }
        public string VARIANTE_NOM { get; set; }
        public Nullable<int> MACHINE_FABRICATION_ID { get; set; }
    
        public virtual MACHINE_FABRICATION MACHINE_FABRICATION { get; set; }
    }
}
