//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTON_INFO
    {
        public int CARTON_INFO_ID { get; set; }
        public string CARTON_INFO_TYPE_CONDITIONNEMENT { get; set; }
        public Nullable<int> CARTON_INFO_QUANTITE { get; set; }
    }
}
