//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdb_data_generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMANDE()
        {
            this.CARTONs = new HashSet<CARTON>();
        }
    
        public int COMMANDE_ID { get; set; }
        public Nullable<int> COMMANDE_NUM_COMMANDE { get; set; }
        public Nullable<bool> COMMANDE_ETAT { get; set; }
        public Nullable<System.DateTime> COMMANDE_DATE_COMMANDE { get; set; }
        public Nullable<System.DateTime> COMMANDE_DATE_FABRICATION { get; set; }
        public Nullable<System.DateTime> COMMANDE_DATE_CONDITIONNEMENT { get; set; }
        public Nullable<System.DateTime> COMMANDE_DATE_EXPEDITION { get; set; }
        public Nullable<decimal> COMMANDE_PRIX_LOT { get; set; }
        public string COMMANDE_CARTON { get; set; }
        public Nullable<int> PAYS_ID { get; set; }
        public Nullable<int> BONBON_ID { get; set; }
        public Nullable<int> CONDITIONNEMENT_ID { get; set; }
    
        public virtual BONBON BONBON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTON> CARTONs { get; set; }
        public virtual PAYS PAY { get; set; }
        public virtual CONDITIONNEMENT CONDITIONNEMENT { get; set; }
    }
}
